services:
  - type: web
    name: auto-commit-backend
    env: python
    buildCommand: pip install -r requirements-deploy.txt
    startCommand: bash ./start.sh
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_SECRET_KEY
        sync: false
      - key: GITHUB_CLIENT_ID
        sync: false
      - key: GITHUB_CLIENT_SECRET
        sync: false
      - key: GITHUB_REDIRECT_URI
        sync: false
      - key: GITHUB_WEBHOOK_SECRET
        sync: false
      - key: WEBHOOK_URL
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: ALLOWED_ORIGINS
        sync: false